### ISSUE TITLE
Request: Make PHP Appveyor builds generate releases for Windows (PECL is not yet providing Windows builds for 8.0)

### ISSUE THREAD

**Issue by swiffer** [igbinary/igbinary#298] opened 2020-10-18 14:05 UTC
thanks adding php8 builds to appveyor. currently they are failing / at least no artifacts are available.

**Comment by TysonAndre** [comment] 2020-10-18 14:52
igbinary has never provided artifacts through appveyor for any current or prior releases - the appveyor jobs are just for unit testing. There'd be 4 builds needed per php minor version if it did (all combinations of NTS/ZTS, and 32/64-bit)

https://pecl.php.net/package/igbinary/3.1.6/windows is the source of Windows builds, and the PECL maintainers don't provide DLLs for PHP 8.0RC yet.

Windows build instructions can be found in the README.

**Comment by TysonAndre** [comment] 2020-10-18 14:56
Part of the issue is that Microsoft is no longer working with the php team to provide Windows builds, so I'm waiting to see what PECL or other extension authors decide in the meantime - https://www.techrepublic.com/article/microsoft-to-discontinue-windows-builds-of-php-programming-language/

I'll wait until php 8.0.0 stable is released in november to see if PECL maintainers update it.

**Comment by TysonAndre** [comment] 2021-01-09 21:06
I checked again today, https://pecl.php.net/package/igbinary/3.2.1/windows was recently updated by the pecl.php.net owners to include dlls for PHP 8.0

If you see any new issues in php 8.0, they should be reported in a different issue

**Closed by TysonAndre** 2021-01-09 21:06 UTC
Labels: question
